enable-magisk-update = true

parallel-jobs = 2
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX-2"

patches-version = "dev"
integrations-version = "dev"

[YouTube]
build-mode = "module"
included-patches = "'Custom header for YouTube'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
patches-version = "v4.14.1-dev.1"
integrations-version = "v1.14.1-dev.1"
build-mode = "module"
included-patches = "'Custom header for YouTube Music'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
