enable-magisk-update = true

parallel-jobs = 2
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX-2"

patches-version = "v2.228.0-dev.14"
integrations-version = "v0.155.0-dev.9"

[YouTube]
build-mode = "module"
excluded-patches = "'Spoof streaming data'"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Visual preferences icons'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "module"
excluded-patches = "'Enable Cairo splash animation'"
included-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom header for YouTube Music' 'Visual preferences icons'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
